require("plugins.telescope")
require("plugins.treesitter")
require("plugins.trouble")
-- require("plugins.lsp")
-- require("plugins.codesnap")
require("plugins.catppuccin")
require("plugins.bufferline")
require("plugins.toggleterm")
-- require("plugins.lualine")
require("plugins.which")
require("plugins.harpoon")
