#!/usr/bin/env python

import subprocess

def main():
    xrandr_out = subprocess.run("xrandr", shell=True, capture_output=True)
    if "eDP-1-1 connected" in str(xrandr_out):
        subprocess.run([
            "xrandr",
            "--output",
            "eDP-1-1",
            "--mode",
            "1920x1080",
            "--rate",
            "144",
            "--dpi",
            "96"
        ], shell=True, capture_output=True)
        subprocess.run([
            "dunstify",
            "set display"
        ])


if __name__ == "__main__":
    main()
