#!/usr/bin/env bash

session=$DESKTOP_SESSION

if [ "$session" == "wayland" ]; then
  layout=$(hyprctl getoption input:kb_layout | rg "str:")
  if [ "$layout" == "str: br, us" ]; then
    notify-send "kbd is now us"
    hyprctl keyword input:kb_layout "us, br"
  else
    notify-send "kbd is now br"
    hyprctl keyword input:kb_layout "br, us"
  fi
else
  kb_format=$(setxkbmap -print -verbose 10 | rg "layout:")

  if [ "$kb_format" == "layout:     us" ]; then
    notify-send "kbd is now br"
    setxkbmap br
  else
    notify-send "kbd is now us"
    setxkbmap us
  fi
fi

