#!/usr/bin/env bash

if [ "$(hyprctl activewindow -j | jq -r ".class")" = "com.github.wwmm.easyeffects" ]; then
  xdotool getactivewindow windowunmap
  notify-send "closing window..."
else
  notify-send "killing window..."
  hyprctl dispatch 'hl.dsp.window.close()'
fi