#!/usr/bin/env bash

dconf write /org/gnome/desktop/interface/color-scheme "'prefer-dark'"
dconf write /org/gnome/desktop/interface/clock-show-seconds true
dconf write /org/gnome/desktop/interface/clock-show-weekday true
dconf write /org/gnome/desktop/notifications/show-banners false

dconf write /org/gnome/desktop/wm/keybindings/switch-input-source "['<Alt>Shift_L']"
# dconf write /org/gnome/desktop/wm/keybindings/switch-input-source-backward "[]"
dconf write /org/gnome/desktop/wm/keybindings/close "['<Super>Q']"

dconf write /org/gnome/desktop/wm/keybindings/panel-run-dialog "['<Alt>F2']"

dconf write /org/gnome/shell/keybindings/show-screenshot-ui "['<Shift><Super>s']"

dconf write /org/gnome/shell/window-switcher/current-workspace-only true
dconf write /org/gnome/shell/app-switcher/current-workspace-only true

dconf write /org/gnome/shell/keybindings/switch-to-application-1 "['']"
dconf write /org/gnome/shell/keybindings/switch-to-application-2 "['']"

dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-left "['<Super>1']"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-right "['<Super>2']"

dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-left "['<Shift><Super>1']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-right "['<Shift><Super>2']"

dconf write /org/gnome/nautilus/preferences/default-folder-viewer "'list-view'"
dconf write /org/gnome/nautilus/preferences/show-hidden-files true

dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/']"

dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name "'Open Nautilus'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command "'nautilus'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding "'<Super>e'"

dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name "'Open Wofi'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command "'wofi'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding "'<Super>R'"

dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/name "'Open Ghostty'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/command "'ghostty'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/binding "'<Super>return'"

dconf write /org/virt-manager/virt-manager/connections/autoconnect "['qemu:///system']"
dconf write /org/virt-manager/virt-manager/connections/uris "['qemu:///system']"

dconf write /org/gnome/desktop/input-sources/sources "[('xkb', 'us'), ('xkb', 'br')]"

dconf write /org/gnome/desktop/wm/preferences/button-layout "'appmenu:minimize,maximize,close'"

dconf write /org/gnome/desktop/interface/enable-animations false
