#!/usr/bin/env bash

pkill dunst
dunst -config ~/.config/dunst/dunstrc &

dunstify -u critical "Text message: critical test 1"
dunstify -u normal "Test message: normal test 2"
dunstify -u low "Test message: low test 3"
dunstify -u critical "Test message: critical test 4"
dunstify -u normal "Test message: normal test 5"
dunstify -u low "Test message: low test 6"
dunstify -u critical "Test message: critical test 7"
dunstify -u normal "Test message: normal test 8"
dunstify -u low "Test message: low test 9"
