source-file ~/.config/tmux/core.conf

# hide the bar
# set -g status off

# Configuração de cores (fundo escuro, fonte azul)
# Cor de fundo principal
set -g status-style "fg=blue,bg=black"

# Janela ativa (carmesim mais escuro)
setw -g window-status-current-format '#[fg=black,bg=#8b0000]#[fg=#d0d0d0,bg=#8b0000] #I #[fg=#d0d0d0,bg=#8b0000] #{b:pane_current_path} #[fg=#8b0000,bg=black,nobold]'

# Janelas inativas (carmesim escuro)
setw -g window-status-format '#[fg=black,bg=black]#[fg=blue,bg=black] #I  #{b:pane_current_path} #[fg=black,bg=black,nobold,nounderscore,noitalics]'

# Bordas dos paineis
set -g pane-border-style 'fg=#3b0a0e,bg=black'
set -g pane-active-border-style 'fg=#8b0000,bg=black'

# Mensagens
set -g message-style "fg=blue,bg=black"
set -g message-command-style "fg=blue,bg=black"

# Barra de status
set -g status-left "#[fg=#d0d0d0,bg=#00008b,bold] #S #[fg=#00008b,bg=#d0d0d0,nobold,nounderscore,noitalics]"
set -g status-right "#[fg=#8b0000,bg=#d0d0d0]#[fg=#d0d0d0,bg=#8b0000] %H:%M #[fg=#00008b,bg=#8b0000]#[fg=#d0d0d0,bg=#00008b] %d-%b-%y "
set -g status-justify "left"
set -g status-left-length "100"
set -g status-right-length "100"
