source-file ~/.config/tmux/core.conf

# hide the bar
set -g status off

# Configuração de cores (fundo escuro, fonte azul)
# Cor de fundo principal
set -g status-style "fg=blue,bg=black"

# Janela ativa (carmesim mais escuro)
setw -g window-status-current-format '#[fg=black,bg=#b21e35]#[fg=#f0f0f0,bg=#b21e35] #I #[fg=#f0f0f0,bg=#b21e35] #{b:pane_current_path} #[fg=#b21e35,bg=black,nobold]'

# Janelas inativas (carmesim escuro)
setw -g window-status-format '#[fg=black,bg=black]#[fg=blue,bg=black] #I  #{b:pane_current_path} #[fg=black,bg=black,nobold,nounderscore,noitalics]'

# Bordas dos paineis
set -g pane-border-style 'fg=#4d0f16,bg=black'
set -g pane-active-border-style 'fg=#b21e35,bg=black'

# Mensagens
set -g message-style "fg=blue,bg=black"
set -g message-command-style "fg=blue,bg=black"

# Barra de status
set -g status-left "#[fg=black,bg=blue,bold] #S #[fg=blue,bg=black,nobold,nounderscore,noitalics]"
set -g status-right "#[fg=#b21e35,bg=black]#[fg=#f0f0f0,bg=#b21e35] %H:%M #[fg=blue,bg=#b21e35]#[fg=black,bg=blue] %d-%b-%y "
set -g status-justify "left"
set -g status-left-length "100"
set -g status-right-length "100"
