#!/usr/bin/env bash

set -euo pipefail

arch_packages=(
  android-file-transfer
  android-studio
  ani-cli
  antimicrox
  arduino-ide-bin
  arm-none-eabi-gcc
  aws-cli
  bat
  bc
  brightnessctl
  blender
  brave-bin
  discord
  distrobox
  docker
  libnotify
  eza
  fastfetch
  firefox
  fish
  flatpak
  fzf
  gimp
  github-cli
  gparted
  graphviz
  grim
  hyprcursor
  hypridle
  hyprland
  hyprlock
  hyprpaper
  hyprpicker
  hyprshot
  inkscape
  jq
  keyd
  lazygit
  less
  libvirt
  lutris
  mako
  mariadb
  mission-center
  mise
  mtpfs
  nautilus
  ncdu
  neovide
  neovim
  nix
  nodejs-ngrok
  noto-fonts
  noto-fonts-cjk
  noto-fonts-emoji
  noto-fonts-extra
  obs-studio
  pamixer
  pandoc-cli
  papirus-icon-theme
  patch
  pavucontrol
  pkgconf
  plantuml
  playerctl
  power-profiles-daemon
  qemu-full
  qmk
  ripgrep
  rofi-wayland
  scrcpy
  sublime-text-4
  swaybg
  syncthing
  tesseract
  tesseract-data-eng
  tesseract-data-por
  ttf-firacode-nerd
  ttf-hack-nerd
  ttf-jetbrains-mono-nerd
  ttf-roboto-mono
  ttf-roboto-mono-nerd
  ttf-ubuntu-nerd
  viewnior
  virt-manager
  visual-studio-code-bin
  vlc
  vlc-plugins-all
  vulkan-icd-loader
  vulkan-tools
  wezterm
  wlogout
  wl-clipboard
  zip
  zoxide
  ghostty
  hyprlauncher
  openai-codex-bin
  claude-code
  wine
  wireplumber
  apollo-git
  herdr-bin
  ddcutil
  gtk4-layer-shell
  bluez
  bluez-utils
  pipewire-pulse
  wireplumber
  pipewire-alsa
  alsa-utils
)

yay -S --needed --noconfirm "${arch_packages[@]}"
# Installs tools declared in ~/.config/mise/config.toml
mise install

# Problematic/optional AUR packages. Install manually when needed.
# yay -S --needed eden-git eh-vial-appimage

sudo mkdir -p /etc/keyd
sudo ln -nfs "$HOME/dotfiles/linux/system/keyd/default.conf" /etc/keyd/default.conf
sudo systemctl enable keyd --now
sudo keyd reload || true

sudo systemctl enable bluetooth --now

sudo systemctl enable docker --now
systemctl enable --user syncthing --now

sudo timedatectl set-timezone America/Bahia
sudo timedatectl set-local-rtc 1
sudo chsh -s /usr/bin/fish rgnh55

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install -y flathub com.github.wwmm.easyeffects

sudo nix-channel --add https://nixos.org/channels/nixpkgs-unstable
sudo nix-channel --update

systemctl enable --user apollo.service --now

sudo modpobre i2c-dev # for monitor
sudo usermod -aG i2c rgnh55
