#!/usr/bin/env bash

yay -S --needed --noconfirm \
  android-file-transfer android-studio ani-cli antimicrox arduino-ide-bin \
  arm-none-eabi-gcc aws-cli bat bc blender brave-bin discord distrobox docker \
  dunst eza fastfetch firefox fish flatpak fzf gimp github-cli gparted graphviz \
  grim hyprcursor hyprland hyprpaper hyprpicker hyprshot inkscape jdk17-openjdk \
  jq keyd lazygit less libvirt lutris mako mariadb maven mission-center mtpfs \
  ncdu neovide neovim nix nodejs-ngrok noto-fonts noto-fonts-cjk noto-fonts-emoji \
  noto-fonts-extra obs-studio pamixer pandoc-cli papirus-icon-theme patch pavucontrol \
  pkgconf plantuml playerctl pnpm power-profiles-daemon qemu-full qmk rembg \
  ripgrep rofi-wayland rust scrcpy steam sublime-text-4 swaybg syncthing \
  tesseract tesseract-data-eng tesseract-data-por ttf-firacode-nerd ttf-hack-nerd \
  ttf-jetbrains-mono-nerd ttf-roboto-mono ttf-roboto-mono-nerd ttf-ubuntu-nerd \
  viewnior virt-manager visual-studio-code-bin vlc vulkan-icd-loader vulkan-tools \
  quickshell wezterm wlogout wl-clipboard zip zoxide ghostty hyprlauncher openai-codex-bin \
  claude-code nautilus wine claude-desktop-bin \
  aylurs-gtk-shell libastal-meta wireplumber \

# Problematic/optional AUR packages. Install manually when needed.
# yay -S --needed eden-git eh-vial-appimage

sudo systemctl enable keyd --now

yay -S bluez bluez-utils pipewire-pulse wireplumber --needed
sudo systemctl enable bluetooth --now

sudo systemctl enable docker --now
systemctl enable --user syncthing --now

sudo timedatectl set-timezone America/Bahia
sudo timedatectl set-local-rtc 1
sudo chsh -s /usr/bin/fish rgnh55

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install -y flathub com.github.wwmm.easyeffects

sudo nix-channel --add https://nixos.org/channels/nixpkgs-unstable
sudo nix-channel --update
