monitor = , 1920x1080@144, 0x0, 1
exec-once = sleep 2 & dunst
exec-once = sleep 2 & emacs --daemon & dunstify "Started emacs daemon"

exec = sleep 1 & randwall & dunstify "Set a random background"
exec = toggle_inner_display_automatically & dunstify "Toggled inner display"

windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

bind = SUPER, Return, exec, ghostty
bind = SUPER, Q, killactive
bind = SUPER, E, exec, nautilus --new-window
bind = SUPER, R, exec, pkill rofi || rofi -show run
bind = SUPER, B, exec, google-chrome-stable
bind = SUPER, P, exec, pavucontrol
bind = SUPER, M, exec, pamixer --default-source -t
bind = SUPER, F, fullscreen
bind = SUPER SHIFT, f, togglefloating

bind = SUPER, o, exec, ocr
bind = SUPER, e, exec, emacsclient -c -a ""
bind = SUPER, k, exec, printkbd
bind = SUPER, Return, exec, neovide
bind = SUPER, u, exec, brightnessctl set 1%+
bind = SUPER, d, exec, brightnessctl set 1%-
bind = SUPER_SHIFT, W, exec, pkill waybar || waybar
bind = SUPER_SHIFT, P, exec, select_wallpaper
bind = SUPER_SHIFT, Q, exec, wlogout
bind = SUPER_SHIFT, S, exec, screenshtarea

bind = SUPER, grave, workspace, 1
bind = SUPER, 1, workspace, 2
bind = SUPER, 2, workspace, 3
bind = SUPER, 3, workspace, 4
bind = SUPER, 4, workspace, 5
bind = SUPER, 5, workspace, 6
bind = SUPER, 6, workspace, 7
bind = SUPER, 7, workspace, 8
bind = SUPER, 8, workspace, 9
bind = SUPER, 9, workspace, 10

bind = SUPER_SHIFT, grave, movetoworkspace, 1
bind = SUPER_SHIFT, 1, movetoworkspace, 2
bind = SUPER_SHIFT, 2, movetoworkspace, 3
bind = SUPER_SHIFT, 3, movetoworkspace, 4
bind = SUPER_SHIFT, 4, movetoworkspace, 5
bind = SUPER_SHIFT, 5, movetoworkspace, 6
bind = SUPER_SHIFT, 6, movetoworkspace, 7
bind = SUPER_SHIFT, 7, movetoworkspace, 8
bind = SUPER_SHIFT, 8, movetoworkspace, 9
bind = SUPER_SHIFT, 9, movetoworkspace, 10

bind = ALT, S, togglespecialworkspace, magic
bind = ALT SHIFT, S, movetoworkspace, special:magic
bind = ALT, mouse_down, workspace, e+1
bind = ALT, mouse_up, workspace, e-1
bindm = ALT, mouse:272, movewindow
bindm = ALT, mouse:273, resizewindow

bind = ALT CTRL, left, resizeactive, -50 0
bind = ALT CTRL, right, resizeactive, 50 0
bind = ALT CTRL, up, resizeactive, 0 -50
bind = ALT CTRL, down, resizeactive, 0 50

bind = ALT, Tab, cyclenext,
bind = ALT, Tab, alterzorder,

windowrulev2 = float, class:(Rofi)

general { 
  gaps_in = 1
  gaps_out = 0
  border_size = 0
  col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
  col.inactive_border = rgba(595959aa)
  resize_on_border = false 
  allow_tearing = false
  layout = dwindle
}

decoration {
  rounding = 7
  active_opacity = 1
  inactive_opacity = 1
  # drop_shadow = false
  # shadow_range = 4
  # shadow_render_power = 3
  # col.shadow = rgba(1a1a1aee)
  blur {
    enabled = false
    size = 3
    passes = 1
    vibrancy = 0.1696
  }
}

animations {
  enabled = false
  bezier = myBezier, 0.05, 0.9, 0.1, 1.05
  animation = windows, 1, 7, myBezier
  animation = windowsOut, 1, 7, default, popin 80%
  animation = border, 1, 10, default
  animation = borderangle, 1, 8, default
  animation = fade, 1, 7, default
  animation = workspaces, 1, 6, default
}

dwindle {
  pseudotile = true 
  preserve_split = true
}

master {
  # new_is_master = true
}

misc { 
  force_default_wallpaper = 0
  disable_hyprland_logo = true 
}

input {
  kb_layout = us, br
  kb_variant =
  kb_model =
  kb_options = grp:alt_shift_toggle, ctrl:nocaps
  kb_rules =
  follow_mouse = 1
  sensitivity = 1
  accel_profile = "flat"
  touchpad {
    natural_scroll = true
  }
}

gestures {
  workspace_swipe = false
}

device {
  name = elan0521:01-04f3:31b1-touchpad
  sensitivity = 0
  accel_profile = "flat"
}

device {
  name = compx-2.4g-dual-mode-mouse
  sensitivity = -0.7
  accel_profile = "flat"
}
