build:
	sudo nixos-rebuild build -I nixos-config=/home/rgnh55/dotfiles/nix-minimal/configuration.nix
switch:
	sudo nixos-rebuild switch -I nixos-config=/home/rgnh55/dotfiles/nix-minimal/configuration.nix
