# https://wiki.hypr.land/Hypr-Ecosystem/hypridle/

general {
    lock_cmd = ~/.local/scripts/lock-screen
    before_sleep_cmd = ~/.local/scripts/lock-screen --wait
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

# listener {
#     timeout = 30
#     on-timeout = ~/.local/scripts/monitor-brightness dim
#     on-resume = ~/.local/scripts/monitor-brightness restore
# }

listener {
    timeout = 300
    on-timeout = ~/.local/scripts/lock-screen
}

listener {
    timeout = 90
    on-timeout = sleep 1 && hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && ~/.local/scripts/monitor-brightness restore
}
