#!/bin/bash
# get the git status of all cwd childs
ORIGINALDIR="${PWD}"
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

for d in *; do
	if [ -d "$d" ]; then
		cd $d
		if [[ -d .git ]]; then
			printf "${GREEN}--- $d ---\n${NC}"
			git status &
			sleep 0.1
		fi
		cd $ORIGINALDIR
	fi
done
