#!/usr/bin/env bash

# hyprctl keyword monitor "DP-1, 1920x1080@144, 0x0, 1"
# hyprctl keyword monitor "HDMI-A-1, 2560x1440@60, 0x0, 1"
hyprctl keyword monitor "HDMI-A-1, 3840x2160@60, 0x0, 1"
hyprctl keyword monitor "eDP-1, 1920x1080@144, 2560x0, 1"
