#!/usr/bin/env bash

# check if number of positional parameters is eq to 1
if [[ $# -eq 1 ]]; then
  selected=$1 # note for future me: bash scripts can't have surrounding spaces in assignment
else
  selected=$(find  ~/sync ~/dotfiles ~/repos ~/repos/gh -mindepth 1 -maxdepth 1 -type d -not -path "*/.stfolder" -not -path "*/.git" | fzf)
fi

# if selected is empty
if [[ -z $selected ]]; then
  exit 0
fi

selected_name=$(basename "$selected")
tmux_running=$(pgrep tmux)

# if tmux is not running
# first, check if $TMUX is set, it stores metadata of the current session
# if i'm on session 0, the last data is it
# second, check if the process is running
if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmux new-session -s $selected_name -c $selected
  exit 0
fi

# if tmux is running
if ! tmux has-session -t=$selected_name 2>/dev/null; then
  tmux new-session -ds $selected_name -c $selected
fi

# execute if tmux is running
tmux switch-client -t $selected_name
